# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 08:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('place_found', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='children/')),
                ('education', models.CharField(blank=True, max_length=5)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('hobby', models.CharField(blank=True, max_length=20)),
                ('adoption_date', models.DateField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('organizer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('established', models.DateTimeField()),
                ('no_of_children', models.CharField(max_length=5)),
                ('area', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.CharField(max_length=6)),
                ('director', models.CharField(max_length=30)),
                ('no_of_staff', models.CharField(max_length=5)),
                ('image', models.FileField(upload_to='ngo/')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='staff/')),
                ('description', models.TextField(blank=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO')),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
        migrations.AddField(
            model_name='children',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
    ]
