# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0002_auto_20180117_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('child_code', models.CharField(max_length=3)),
                ('aadhar_no', models.CharField(max_length=20)),
                ('pan_card', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=10)),
                ('donor_paid', models.CharField(max_length=5)),
                ('last_paid', models.DateField()),
                ('total_paid', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=20)),
            ],
        ),
    ]
