# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0003_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='image',
            field=models.ImageField(blank=True, upload_to='donor/'),
        ),
    ]
