# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0004_donor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donation_amount', models.CharField(max_length=10)),
                ('month', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=3)),
                ('certificate_issue_date', models.DateField()),
                ('sponsored_child_code', models.CharField(max_length=100)),
                ('sponsored_child_name', models.CharField(max_length=100)),
                ('ngo_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO')),
            ],
        ),
    ]
