# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0005_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='month',
            field=models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=10),
        ),
    ]
