# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0009_auto_20180125_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
