# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0010_children_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='link',
        ),
        migrations.AddField(
            model_name='children',
            name='video_link',
            field=models.URLField(blank=True),
        ),
    ]
