# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0011_auto_20180130_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='photos',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
