# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0018_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='children/'),
        ),
    ]
