# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0020_auto_20180131_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
