# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0021_auto_20180131_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(),
        ),
    ]
