# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0022_auto_20180131_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
    ]
