# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 08:30
from __future__ import unicode_literals

import NGO.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NGO', '0026_auto_20180206_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='image',
            field=models.ImageField(upload_to='children/', validators=[NGO.validators.validate_file_size]),
        ),
    ]
