# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO', '0006_auto_20180120_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_code', models.CharField(max_length=100)),
                ('donor_id', models.CharField(max_length=100)),
                ('invoice', models.FileField(blank=True, upload_to='')),
                ('donation_month', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=10)),
                ('date', models.DateField()),
                ('paid', models.CharField(max_length=10)),
                ('select_ngo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO')),
            ],
        ),
    ]
