# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('NGO', '0023_remove_events_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('child_code', models.CharField(max_length=6)),
                ('donor_id', models.CharField(max_length=100)),
                ('donation_month', models.CharField(choices=[('jan', 'January'), ('feb', 'February'), ('mar', 'March'), ('apr', 'April'), ('may', 'May'), ('jun', 'June'), ('jul', 'July'), ('aug', 'August'), ('sep', 'September'), ('oct', 'October'), ('nov', 'November'), ('dec', 'December')], max_length=10)),
                ('date', models.DateField()),
                ('paid', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('select_ngo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO')),
            ],
        ),
    ]
