# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='time_stamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
