# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20180201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='time_stamp',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
