# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20180122_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='child_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NGO.Children'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='select_ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NGO.NGO'),
        ),
    ]
