# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20180201_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_id', models.CharField(max_length=100)),
                ('donor_country', models.CharField(choices=[('us', 'USA'), ('india', 'INDIA'), ('aus', 'Australia')], max_length=10)),
                ('donor_full_address', models.CharField(max_length=250)),
                ('donor_image', models.ImageField(upload_to='DonorList/')),
                ('joined', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
