# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(auto_created=True, max_length=100),
        ),
    ]
