# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_auto_20180131_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='child_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NGO.Children'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='select_ngo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NGO.NGO'),
        ),
    ]
