# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_auto_20180206_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
