# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-06 06:43
from __future__ import unicode_literals

from django.db import migrations
import shortuuidfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_auto_20180206_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, default=uuid.uuid4, editable=False, max_length=22, unique=True),
        ),
    ]
