# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_auto_20180206_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='child_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
